# -*- Mode: YAML -*-

sudo: false # request container-base infrastructure
language: cpp

cache:
  apt: true
  directories:
    - ${HOME}/extra

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-sdk-team
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - boost-latest
          packages:
            - cmake
            - cmake-data
            - doxygen
            - git
            - graphviz
            - libboost1.55-all-dev
            - libfltk1.3-dev
            - libgtkmm-3.0-dev
            - qtbase5-dev
            - g++-5
      env:
        - MATRIX_CC=gcc-5
        - MATRIX_CXX=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-sdk-team
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
            - boost-latest
          packages:
            - cmake
            - cmake-data
            - doxygen
            - git
            - graphviz
            - libboost1.55-all-dev
            - libfltk1.3-dev
            - libgtkmm-3.0-dev
            - qtbase5-dev
            - clang-3.7
      env:
        - MATRIX_CC=clang-3.7
        - MATRIX_CXX=clang++-3.7
      
before_script:
  - export CC=${MATRIX_CC} && ${CC} --version
  - export CXX=${MATRIX_CXX} && ${CXX} --version
  - mkdir ${TRAVIS_BUILD_DIR}/extra
  - export GLI_ROOT_DIR=${TRAVIS_BUILD_DIR}/extra/gli-git
  - export GLM_ROOT_DIR=${TRAVIS_BUILD_DIR}/extra/glm-git
  - git clone --depth 1 http://github.com/g-truc/gli.git ${GLI_ROOT_DIR}
  - git clone --depth 1 http://github.com/g-truc/glm.git ${GLM_ROOT_DIR}
  - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3 # give xvfb some time to start
  - mkdir ${TRAVIS_BUILD_DIR}/build
  
script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake ..
  - cmake --build .
